In [1]:
# Importa bibliotecas necessarias 
import numpy as np
import urllib
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import  model_selection
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import pydotplus
from sklearn.preprocessing import LabelEncoder

/home/svncjus/anaconda3/lib/python3.7/site-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


In [2]:
dataset = pd.read_csv('abalone.data', sep=",", header=None)
dataset.columns = ["sex", "length", "diameter", "height","whole height","shucked weight","viscera weight","shell weight","rings"]

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sex             4177 non-null   object 
 1   length          4177 non-null   float64
 2   diameter        4177 non-null   float64
 3   height          4177 non-null   float64
 4   whole height    4177 non-null   float64
 5   shucked weight  4177 non-null   float64
 6   viscera weight  4177 non-null   float64
 7   shell weight    4177 non-null   float64
 8   rings           4177 non-null   int64  
dtypes: float64(7), int64(1), object(1)
memory usage: 293.8+ KB


dataset.groupby(['rings']).count()

In [4]:
dataset.head()

sex  length  diameter  height  whole height  shucked weight  viscera weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   shell weight  rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [5]:
# Imprime quantide de instancias e atributos da base
print("Instancias e atributos")
print(dataset.shape)

Instancias e atributos
(4177, 9)


In [6]:
for label in dataset.columns:
    dataset[label] = LabelEncoder().fit(dataset[label]).transform(dataset[label])

In [7]:
dataset=dataset.to_numpy()

In [8]:
print(dataset)

[[  2  66  56 ... 199 263  14]
 [  2  45  36 ...  94 113   6]
 [  0  81  67 ... 280 374   8]
 ...
 [  2  95  78 ... 571 550   8]
 [  0 100  80 ... 518 530   9]
 [  2 117  94 ... 732 813  11]]


In [9]:
X = dataset[:,1:8]
y = dataset[:,0]

In [10]:
# EXEMPLO USANDO HOLDOUT
# Holdout -> dividindo a base em treinamento (70%) e teste (30%), estratificada
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.3, random_state=42)

In [11]:
# declara o classificador
clfa = KNeighborsClassifier(n_neighbors=3)

NameError: name 'KNeighborsClassifier' is not defined

In [ ]:
# treina o classificador
clfa = clfa.fit(X_train, y_train)

In [ ]:
#testa usando a base de testes
predicted=clfa.predict(X_test)

In [ ]:
# calcula a acuracia na base de teste (taxa de acerto)
score=clfa.score(X_test, y_test)

In [ ]:
# calcula a matriz de confusao
matrix = confusion_matrix(y_test, predicted)

In [ ]:
# apresenta os resultados
print("\nResultados baseados em Holdout 70/30")
print("Taxa de acerto = %.2f " % score)
print("Matriz de confusao:")
print(matrix)

In [ ]:
# EXEMPLO USANDO VALIDACAO CRUZADA
clfb = KNeighborsClassifier(n_neighbors=3)
folds=5
result = model_selection.cross_val_score(clfb, X, y, cv=folds)

In [ ]:
print("\nResultados baseados em Validacao Cruzada")
print("Qtde folds: %d:" % folds)
print("Taxa de Acerto: %.2f" % result.mean())
print("Desvio padrao: %.2f" % result.std())

In [ ]:
# matriz de confusão da validacao cruzada
Z = model_selection.cross_val_predict(clfb, X, y, cv=folds)
cm=confusion_matrix(y, Z)
print("Matriz de confusao:")
print(cm)